### ISSUE TITLE
No audio downloaded for this book?

### ISSUE THREAD

**Issue by 2600box** [NicoWeio/blinkist#3]
Hello,

Love this tool! 

Is there any way to get a verbose or debug log?

This book downloads no audio: https://www.blinkist.com/en/books/the-culture-map-en

It shows downloading chapters, and then this final result:

```
./main.py -r --book-slug the-culture-map-en ./
Book: “The Culture Map”
```
```
~/blinkist/the-culture-map-en# ls -l
total 218
-rw-r--r-- 1 root root  21185 Jan 13 18:25 book.md
-rw-r--r-- 1 root root  25892 Jan 13 18:25 book.yaml
-rw-r--r-- 1 root root 186744 Jan 13 18:25 cover.jpg
```

**Comment by 2600box** [comment]
In the yml there is some interesting empty fields:

```
audioUrl: null
  audio_url: null
  order_no: 0
  signed_audio_url: null
  audio_url: null
  order_no: 1
  signed_audio_url: null

  audio_url: null
  order_no: 2
  signed_audio_url: null

  audio_url: null
  order_no: 3
  signed_audio_url: null
  

  audio_url: null
  order_no: 4
  signed_audio_url: null

  audio_url: null
  order_no: 5
  signed_audio_url: null
  
  audio_url: null
  order_no: 6
  signed_audio_url: null
  
  audio_url: null
  id: 54451f8e6161330008640000
  order_no: 7
  signed_audio_url: null
 
  audio_url: null
  id: 54451fb16161330008660000
  order_no: 8
  signed_audio_url: null
 
  audio_url: null
  id: 54451fdd6161330008680000
  order_no: 9
  signed_audio_url: null

chaptersLength: 8
freeDaily: null
hasAudio: false

isAudio: false
isFree: false
kind: book
language: en
minutesToRead: 15
playUrl: 

```
